name: Lighthouse CI
on:
  push:
    branches:
      - better

env:
  PNPM_VERSION: '9.1.4'
  env_var: 'dev'
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://testing-40917.web.app/#/
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
          budgetPath: .github/lighthouse/budget.json
          configPath: .github/lighthouse/lighthouserc.json
          runs: 3